name: Test

on:
  workflow_dispatch:

#        brew install colima@0.5.6

jobs:
  test:
    runs-on: macos-13
    steps:
    - name: Install deps
      run: |
        brew install docker
        sudo curl -L -o /usr/local/bin/colima https://github.com/abiosoft/colima/releases/download/v0.5.6/colima-Darwin-x86_64 && sudo chmod +x /usr/local/bin/colima
        colima start --network-address
#    - name: Setup Docker on macOS
#      uses: douglascamata/setup-docker-macos-action@v1-alpha
#      with:
#        colima-network-address: true
#    - name: Setup Docker on macOS
#      uses: docker-practice/actions-setup-docker@master
#      timeout-minutes: 12
    - uses: actions/checkout@v4
    - name: Test
      run: |
        ./start.sh
        sleep 10
        docker ps
        docker logs nc_webdav_ubuntu_2004
        netstat -anvp tcp | awk 'NR<3 || /LISTEN/'
        colima status
        curl 'http://127.0.0.1:9080/webdav'


#        curl 'http://localhost:9080/webdav'
#        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "$(brew --prefix colima)/bin/colima"
